#!/usr/bin/env python3
"""Regenerate crates/providers/src/s3/prices.rs from the public AWS Price List.

Downloads the S3 and S3 Glacier Deep Archive offer files for every region (no AWS
credentials needed) and writes the per-GB-month storage list prices that
CloudDirStat uses for its monthly cost estimates.

Usage: python scripts/update_s3_prices.py
"""

import json
import re
import urllib.request
from pathlib import Path

PRICING = "https://pricing.us-east-1.amazonaws.com"
OUTPUT = Path(__file__).resolve().parent.parent / "crates/providers/src/s3/prices.rs"
REGION_CODE = re.compile(r"^[a-z]{2}(-gov)?-[a-z]+-\d$")
USAGE_PREFIX = re.compile(r"^[A-Z]{2,4}\d?-")

# Rust field name -> usage type (without the region prefix).
S3_USAGE_TYPES = {
    "standard": "TimedStorage-ByteHrs",
    "intelligent_tiering": "TimedStorage-INT-FA-ByteHrs",
    "standard_ia": "TimedStorage-SIA-ByteHrs",
    "onezone_ia": "TimedStorage-ZIA-ByteHrs",
    "glacier_ir": "TimedStorage-GIR-ByteHrs",
    "glacier": "TimedStorage-GlacierByteHrs",
    "reduced_redundancy": "TimedStorage-RRS-ByteHrs",
    "express_onezone": "TimedStorage-XZ-ByteHrs",
    "int_monitoring_per_object": "Monitoring-Automation-INT",
}
DEEP_ARCHIVE_USAGE_TYPES = {"deep_archive": "TimedStorage-GDA-ByteHrs"}
FIELDS = [*S3_USAGE_TYPES, *DEEP_ARCHIVE_USAGE_TYPES]


def fetch(path):
    with urllib.request.urlopen(PRICING + path) as response:
        return json.load(response)


def region_urls(offer):
    regions = fetch(f"/offers/v1.0/aws/{offer}/current/region_index.json")["regions"]
    return {code: info["currentVersionUrl"] for code, info in regions.items() if REGION_CODE.match(code)}


def first_tier_prices(offer_file, usage_types):
    """Price of the first volume tier (beginRange 0) for each wanted usage type."""
    wanted = {usage: field for field, usage in usage_types.items()}
    terms = offer_file["terms"]["OnDemand"]
    prices = {}
    for sku, product in offer_file["products"].items():
        usage = USAGE_PREFIX.sub("", product["attributes"].get("usagetype", ""), count=1)
        field = wanted.get(usage)
        if field is None:
            continue
        for term in terms.get(sku, {}).values():
            for dimension in term["priceDimensions"].values():
                if dimension["beginRange"] == "0":
                    prices[field] = float(dimension["pricePerUnit"]["USD"])
    return prices


def rust_option(value):
    return "None" if value is None else f"Some({value!r})"


def main():
    s3 = region_urls("AmazonS3")
    deep_archive = region_urls("AmazonS3GlacierDeepArchive")
    published = None
    table = {}
    for region in sorted(s3):
        print(f"fetching {region}")
        offer = fetch(s3[region])
        published = published or offer["publicationDate"][:10]
        prices = first_tier_prices(offer, S3_USAGE_TYPES)
        if region in deep_archive:
            prices |= first_tier_prices(fetch(deep_archive[region]), DEEP_ARCHIVE_USAGE_TYPES)
        if "standard" in prices:
            table[region] = prices

    lines = [
        "// Generated by scripts/update_s3_prices.py from the AWS Price List. Do not edit by hand.",
        "// Storage prices are USD per GB-month (first volume tier); the monitoring fee is per object.",
        "",
        "use super::pricing::RegionPrices;",
        "",
        f'pub const PUBLISHED: &str = "{published}";',
        "",
        "pub const REGIONS: &[RegionPrices] = &[",
    ]
    for region, prices in table.items():
        lines.append("    RegionPrices {")
        lines.append(f'        region: "{region}",')
        for field in FIELDS:
            lines.append(f"        {field}: {rust_option(prices.get(field))},")
        lines.append("    },")
    lines.append("];")
    OUTPUT.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    print(f"wrote {len(table)} regions to {OUTPUT}")


if __name__ == "__main__":
    main()
