#!/usr/bin/env python3
"""Regenerate crates/providers/src/azure/prices.rs from the Azure Retail Prices API.

Downloads the public prices of Blob Storage in general-purpose v2 accounts (no Azure
credentials needed) and writes, per region and redundancy, the per-GB-month list
price of each access tier and the price of listing, which CloudDirStat uses for its
cost estimates.

Usage: python scripts/update_azure_prices.py
"""

import datetime
import json
import time
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path

API = "https://prices.azure.com/api/retail/prices"
FILTER = (
    "serviceName eq 'Storage' and productName eq 'General Block Blob v2' "
    "and priceType eq 'Consumption'"
)
OUTPUT = Path(__file__).resolve().parent.parent / "crates/providers/src/azure/prices.rs"
TIERS = ["hot", "cool", "cold", "archive"]
REDUNDANCIES = ["LRS", "ZRS", "GRS", "RA-GRS", "GZRS", "RA-GZRS"]
LIST_METER = " List and Create Container Operations"


def fetch_json(url, attempts=6):
    """GETs a page, waiting and retrying when the API is busy (429) or failing (5xx)."""
    for attempt in range(1, attempts + 1):
        try:
            with urllib.request.urlopen(url) as response:
                return json.load(response)
        except urllib.error.HTTPError as error:
            busy = error.code == 429 or error.code >= 500
            if not busy or attempt == attempts:
                raise
            retry_after = error.headers.get("Retry-After", "")
            wait = int(retry_after) if retry_after.isdigit() else min(5 * 2 ** (attempt - 1), 60)
            print(f"HTTP {error.code}, retrying in {wait}s ({attempt}/{attempts - 1})", flush=True)
            time.sleep(wait)


def items():
    url = API + "?" + urllib.parse.urlencode({"$filter": FILTER})
    pages = 0
    while url:
        page = fetch_json(url)
        pages += 1
        print(f"fetched page {pages}", flush=True)
        yield from page["Items"]
        url = page.get("NextPageLink")


def collect():
    """{(region, redundancy): {"hot": price, ..., "list_per_10k": price}}"""
    prices = {}
    for item in items():
        region = item["armRegionName"]
        meter = item["meterName"]
        sku = item["skuName"].split(" ", 1)
        if not region or len(sku) != 2 or item["tierMinimumUnits"] != 0:
            continue
        tier, redundancy = sku[0].lower(), sku[1]
        if redundancy not in REDUNDANCIES:
            continue
        row = prices.setdefault((region, redundancy), {})
        if meter == f"{sku[0]} {redundancy} Data Stored" and item["unitOfMeasure"] == "1 GB/Month":
            row[tier] = item["retailPrice"]
        elif meter.endswith(LIST_METER) and tier == "hot" and item["unitOfMeasure"] == "10K":
            row["list_per_10k"] = item["retailPrice"]
    return {key: row for key, row in prices.items() if "hot" in row}


def check(prices):
    """Stops if the prices do not look like Blob Storage prices."""
    hot = prices.get(("eastus", "LRS"), {}).get("hot")
    if hot is None or not 0.01 <= hot <= 0.05:
        raise SystemExit(f"eastus Hot LRS: got {hot}, expected about 0.02")
    if len({region for region, _ in prices}) < 30:
        raise SystemExit("fewer than 30 regions: the API response changed?")


def rust_option(value):
    return "None" if value is None else f"Some({value!r})"


def main():
    prices = collect()
    check(prices)
    rows = []
    for region, redundancy in sorted(prices):
        row = prices[(region, redundancy)]
        fields = "\n".join(f"        {tier}: {rust_option(row.get(tier))}," for tier in TIERS)
        rows.append(
            "    RedundancyPrices {\n"
            f'        region: "{region}",\n'
            f'        redundancy: "{redundancy}",\n'
            f"{fields}\n"
            f"        list_per_10k: {rust_option(row.get('list_per_10k'))},\n"
            "    },"
        )
    today = datetime.date.today().isoformat()
    body = "\n".join(rows)
    source = f"""// Generated by scripts/update_azure_prices.py from the Azure Retail Prices API. Do not
// edit by hand. Storage prices are USD per GB-month (first volume tier); listing is per
// 10,000 operations.

use super::pricing::RedundancyPrices;

pub const PUBLISHED: &str = "{today}";

/// Blob Storage in general-purpose v2 accounts, by region and redundancy.
pub const PRICES: &[RedundancyPrices] = &[
{body}
];
"""
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(source, encoding="utf-8", newline="\n")
    regions = len({region for region, _ in prices})
    print(f"wrote {OUTPUT} ({regions} regions, {len(prices)} region and redundancy pairs)")


if __name__ == "__main__":
    main()
